import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f7f7f5',
  '--slot4-page-text': '#171717',
  '--slot4-panel-bg': '#ffffff',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#5a5a5a',
  '--slot4-soft-muted-text': '#777777',
  '--slot4-accent': '#03AED2',
  '--slot4-accent-fill': '#03AED2',
  '--slot4-accent-soft': '#F8DE22',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#D12052',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#e7e7e7',
  '--slot4-cream': '#ffffff',
  '--slot4-warm': '#fafafa',
  '--slot4-lavender': '#ffe5ec',
  '--slot4-gray': '#f0f0f0',
  '--slot4-body-gradient': 'linear-gradient(180deg,#fbfbf6 0%,#f1f3f4 100%)',
  '--editable-page-bg': '#f7f7f5',
  '--editable-page-text': '#171717',
  '--editable-container': '1120px',
  '--editable-border': '#d7d7d7',
  '--editable-nav-bg': '#03AED2',
  '--editable-nav-text': '#F8DE22',
  '--editable-nav-active': '#F8DE22',
  '--editable-nav-active-text': '#D12052',
  '--editable-cta-bg': '#F8DE22',
  '--editable-cta-text': '#D12052',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#D12052',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_10px_24px_rgba(0,0,0,0.08)]',
  shadowStrong: 'shadow-[0_18px_48px_rgba(0,0,0,0.18)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-10 sm:py-12 lg:py-14',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-8 lg:grid-cols-[1.2fr_0.8fr]',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[200px] shrink-0 snap-start sm:w-[220px]',
  },
  type: {
    eyebrow: 'text-[11px] font-black uppercase tracking-[0.2em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-black leading-[0.94] tracking-[-0.05em] sm:text-5xl lg:text-[3.6rem]',
    sectionTitle: 'text-3xl font-black tracking-[-0.04em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: 'inline-flex items-center justify-center gap-2 rounded-none bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-black uppercase tracking-[0.08em] text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-110',
    secondary: 'inline-flex items-center justify-center gap-2 rounded-none border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-black uppercase tracking-[0.08em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)]',
    accent: 'inline-flex items-center justify-center gap-2 rounded-none bg-[var(--slot4-accent-soft)] px-6 py-3 text-sm font-black uppercase tracking-[0.08em] text-[#D12052] transition duration-200 hover:translate-y-[-1px]',
  },
  media: {
    frame: `relative overflow-hidden ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_36px_rgba(0,0,0,0.14)]',
    fade: 'transition duration-300 hover:opacity-85',
  },
} as const

export const aiLayoutRules = [
  'Keep the white central canvas and the blue/yellow portal header as the dominant visual anchors.',
  'Favor mixed editorial blocks over uniform cards so the page feels hand-arranged.',
  'Use postHref() for every post link so task-specific routing remains intact.',
  'Render every post defensively with image, summary, and category fallbacks.',
  'Preserve responsive behavior by collapsing multi-column portal sections into a readable vertical stack on mobile.',
] as const
